/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Dialog: typeof import('./src/components/Dialog/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    LoadMore: typeof import('./src/components/LoadMore/index.vue')['default']
    Notice: typeof import('./src/components/Notice/index.vue')['default']
    PickerCheckbox: typeof import('./src/components/PickerCheckbox/index.vue')['default']
    PickerPro: typeof import('./src/components/PickerPro/index.vue')['default']
    PickerUtrill: typeof import('./src/components/PickerUtrill/index.vue')['default']
    Popup: typeof import('./src/components/Popup/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./src/components/TabBar/index.vue')['default']
  }
}
